### ISSUE TITLE
[Feature] “Add support for ollama, gemini, etc.”

### ISSUE THREAD

**Issue by Zer0xPoint** [openai-translator/bob-plugin-openai-translator#121] opened 2024-11-25 15:55 UTC
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

add support for other model

### 描述 Motivation

add api or local port support

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment] 2024-11-26 01:41
[Ollama has supported](https://github.com/openai-translator/bob-plugin-openai-translator/issues/116), [duplicate of Gemini](https://github.com/openai-translator/bob-plugin-openai-translator/issues/103).

**Closed by liby** 2024-11-26 01:41 UTC
Labels: enhancement
